#!/usr/bin/env ruby

require "methadone"
require "gentimewheel"

include Methadone::Main
include Methadone::CLILogging

main do |*zones|
  zones.each {|zone| GenTimeWheel::Zone.new(zone)}
  GenTimeWheel.generate(GenTimeWheel::Zone.zones, options[:output])
end

version GenTimeWheel::VERSION
description "Generate TimeWheel image"
arg         :zone, :many, "zones to add to the TimeWheel"

on("-o FILE", "--output", "Save output into the FILE")

go!
